AWSTemplateFormatVersion: '2010-09-09'
Description: "flows http"
Resources:
  receiverFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: receiver
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs8.10
      Timeout: 300
  receiverLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${receiverFunction}"
      RetentionInDays: 7
  receiveformdataFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: receiveformdata
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs8.10
      Timeout: 300
  receiveformdataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${receiveformdataFunction}"
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ receiverFunction , Arn ]
              - Fn::GetAtt: [ receiveformdataFunction , Arn ]
Outputs:
  receiverFunction:
    Description: 'receiver'
    Value:
      Fn::GetAtt: [ receiverFunction , Arn ]
  receiverRole:
    Description: 'receiver'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  receiveformdataFunction:
    Description: 'receiveformdata'
    Value:
      Fn::GetAtt: [ receiveformdataFunction , Arn ]
  receiveformdataRole:
    Description: 'receiveformdata'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
